### ISSUE TITLE
Can't find buttons textures

### ISSUE THREAD

**Issue by manuelx98** [AdrienTD/XXL-Editor#3]
In the old Editor (XXL Editor Preview 2) I was able to find buttons textures when browsing in (almost) any main .KWN in /Home/Local/Graphic things/CManager2D/0: CManager 2D/, however I wasn't able to export them in any way (even with Export all).
In this Editor I cannot even find them anywhere, I looked in every level and texture sector, but they aren't there. I found something in Objects/Level/Graphical stuff/, but I can't seem to do anything with them.

I was trying to export them, edit them with proper controller buttons textures and reimport them.

**Comment by AdrienTD** [comment]
The controller buttons are in the fonts inside the LLOC which you can extract and edit per language in the Localization window (Main > Localization > Font textures). However this only works with XXL 1 PC and GameCube, not XXL2/OG/...

**Comment by manuelx98** [comment]
> The controller buttons are in the fonts inside the LLOC which you can extract and edit per language in the Localization window (Main > Localization > Font textures). However this only works with XXL 1 PC and GameCube, not XXL2/OG/...

Owh, I was working on XXL 2 PC. Alright, thank you anyway, hope to see XXL 2 support too added in the future.

**Comment by AdrienTD** [comment]
I just added localization support for XXL2 as well as Olympic Games, if you're still interested you can try using the latest build: https://ci.appveyor.com/project/AdrienTD/xxl-editor/build/artifacts

Feel free to report any issues you encounter :) (there might be some UI inconsistencies atm, but it should at least open and save correctly, and modded loc files should work fine in-game)

**Comment by manuelx98** [comment]
> I just added localization support for XXL2 as well as Olympic Games, if you're still interested you can try using the latest build: https://ci.appveyor.com/project/AdrienTD/xxl-editor/build/artifacts
> 
> Feel free to report any issues you encounter :) (there might be some UI inconsistencies atm, but it should at least open and save correctly, and modded loc files should work fine in-game)

It works, thank you! Is there a way to share the changes made as a patch of some sort, to not share my entire loc set?

**Comment by AdrienTD** [comment]
@manuelx98 Do you mean you want to distribute one language without the others?

In that case, yeah, that might be tricky.

If you added/removed a new language, there is a counter of languages that is stored ___in every GLOC file___ and needs to be changed (basically adding/removing a language changes the GLOC of the other languages). Thus if you distribute your language you might need to distribute the GLOC and LLOC files of all languages to ensure that the language count is consistent in every GLOC file when the user installs your lang.

So if you want to distribute a single language, the safest would be to remove all other languages, and only distribute the 00GLOC and 00LLOC* files. When the user installs your patch, they will only have one language available, which might be inconvenient, but it should work no matter the version they were using (Multi5, Polish, Russian, ...).

Another possibility might be to keep the original count of languages (5 for XXL2), and make your changes to the first language (French), and only distribute the 00GLOC and 00LLOC* files. This might also work but it does assume that the user also had 5 languages before (which I believe is the case for all versions of the XXL2, but for Olympic Games there were versions with 5 and 6 languages so that method wouldn't really work).

**Comment by manuelx98** [comment]
I understand. No, I meant more like a patch system that would contain only the changes made and could be applied over all languages within XXL-Editor, so everyone could share just a single universal patch and not (I believe?) copyrighted files, but that would be more suitable in a feature request.

**Comment by AdrienTD** [comment]
No, the editor doesn't have any patching system, and that probably wouldn't be trivial to implement. You could use something like Xdelta if you want to make patch files, but this again assumes the user has the same exact version you made the patch with (which might or might not be the case), and the language files are generally small, I don't think you will get into trouble if you distribute them (the original developers/publishers no longer exist, those who made the remasters probably don't care, ...). And it's not like you would distribute the entire game neither.
