### ISSUE TITLE
Crash editor when load changed level

### ISSUE THREAD

**Issue by MrNails** [AdrienTD/XXL-Editor#4]
Editr crash when I load changed level.
I change level adding new Beacons and when I load level again - editro crash.
When I changed other settings - all are Ok.

Game can handle new Beacons, but not Editor.

**Comment by AdrienTD** [comment]
Hmm, I just did a quick test with XXL1, and when I add helmets, save and reload, the editor doesn't crash.

Could you please give me the steps on how to reproduce the crash? And which game were you modding? (And in which level did you add the beacon?)

**Comment by MrNails** [comment]
I did some research and realized that in normal case, when I add one Beacon - it's ok. I can save and load specified level. But when I add other Beacons - editor crash. 

Here my video with demonstrate this bug: https://youtu.be/mjKlZYgb5Ig.
If video have bad quality - it could be still processing hd format.

**Comment by AdrienTD** [comment]
Ah, so you also remove the beacon you just added and then add a new one?

Just tested, and yes, I can confirm that if you remove the beacon you just added and save then reload, it crashes.

I will have to investigate that...

**Comment by AdrienTD** [comment]
Ok, I just fixed it. Check the latest version (v0.2.54) :)

Note that this is more a hotfix: When you remove a beacon, it's cluster that contained the beacon won't be removed even if it is empty. And the editor crashed before due to the empty cluster while rendering. Maybe in the future I might make the editor automatically remove the clusters when empty, but for now this fix is enough. I still recommend to avoid removing beacons as much as possible :)

Thanks for reporting this issue as it was not really obvious to me to find out since I often load levels from scratch :)
