### ISSUE TITLE
Free control setting

### ISSUE THREAD

**Issue by Ricco95** [AdrienTD/XXL-Editor#5]
good time of day. XXL 1 and 2 remastered have problems regarding control settings. so for example. I always use Control as a jump button, but in XXL this is not possible when the button is pressed, subsequent actions are blocked, i.e. when the Asterix key is pressed, it can jump, but forward movement during the jump is blocked if Rcontrol is pressed. also, you cannot use symbols for reassignment, but only letters. are there mods that can fix this? Unfortunately, I can only play with one hand, I had no problems with the original game, but after buying Remastered, I was disappointed because I couldn't play it comfortably, as it was with the original game in 2005.

**Comment by AdrienTD** [comment]
No, there is no mod to fix controls afaik, and not sure if anyone would bother doing it. You might try asking the [Microids support team](https://support.microids.com) for a fix, but it will take them a while to actually do something if they actually will/can.

You could try using a [key remapping tool](https://www.pcgamingwiki.com/wiki/Glossary:Remapping) to e.g. map the Ctrl key to a letter key, and maybe that could fix the issue, not sure though.

I know the Remaster is not of best quality, with plenty of bugs, and the developers didn't give a shit to improve the control settings back then, so it's probably better to just play the originals.

Closing this since this has nothing to do with the XXL Editor.
